### ISSUE TITLE
JOSS: installation

### ISSUE THREAD

**Issue by bonh** [mjcarley/blaswrap#1]
In the `README` it says to execute `. autogen.sh`. However, that doesn't work for me. Executing `./autogen.sh` runs it but returns:
```
./autogen.sh 
configure.ac:53: installing './compile'
configure.ac:68: installing './config.guess'
configure.ac:68: installing './config.sub'
configure.ac:34: installing './install-sh'
configure.ac:34: installing './missing'
configure.ac:39: error: required file 'config.h.in' not found
tests/Makefile.am: installing './depcomp'
```

**Comment by mjcarley** [comment]
On 2023-12-12 10:28, Henning Bonart wrote:
> In the README it says to execute . autogen.sh. However, that doesn't
> work for me. Executing ./autogen.sh runs it but returns:
> 
> ./autogen.sh
> configure.ac:53: installing './compile'
> configure.ac:68: installing './config.guess'
> configure.ac:68: installing './config.sub'
> configure.ac:34: installing './install-sh'
> configure.ac:34: installing './missing'
> configure.ac:39: error: required file 'config.h.in' not found
> tests/Makefile.am: installing './depcomp'

This seems to be a problem with autotools (the autoreconf works fine on 
my system using the github repository). I have rewritten the autogen.sh 
script to make autoreconf force regeneration of all files which seems to 
have fixed the problem.

**Comment by bonh** [comment]
Now I'm getting an additional error: 

```
./autogen.sh

configure.ac:48: installing './compile'
configure.ac:48: installing './config.guess'
configure.ac:48: installing './config.sub'
configure.ac:34: installing './install-sh'
configure.ac:48: error: required file './ltmain.sh' not found
configure.ac:34: installing './missing'
configure.ac:39: error: required file 'config.h.in' not found
tests/Makefile.am: installing './depcomp'
```

**Comment by bonh** [comment]
Following https://www.gnu.org/software/automake/manual/1.9/html_node/Libtool-Issues.html running `libtoolize` removes the first error but the second error persists.
```
libtoolize

./autogen.sh         
                         
configure.ac:48: installing './compile'
configure.ac:48: installing './config.guess'
configure.ac:48: installing './config.sub'
configure.ac:34: installing './install-sh'
configure.ac:34: installing './missing'
configure.ac:39: error: required file 'config.h.in' not found
tests/Makefile.am: installing './depcomp'
```

**Comment by mjcarley** [comment]
I've modified autogen.sh. It works when I clone from github, so it should be okay now.

**Comment by bonh** [comment]
Running configure after autogen gives "./configure: line 12251: ACX_BLAS: command not found".

Removing line 72: ACX_BLAS form configure.ac makes it work but I'm not sure what that does.

**Comment by mjcarley** [comment]
ACX_BLAS is an m4 macro which locates BLAS and sets up the linker options. It is contained in acx_blas.m4 which is in the main directory and found by default on my system. I have now moved it into the m4 directory of blaswrap where it should be found by autoconf, etc.
